import Head from 'next/head';
import styled from 'styled-components';
import Header from '../components/header';

const AppContainer = styled.div`
  max-width: 1920px;
  height: 100vh;
  margin: 0 auto;
  padding: 0 15px;
`;

export default function Home() {
  return (

    <AppContainer>
      <Head>
        <title>Component Library</title>
        <meta name="Michael Cuccia" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </AppContainer>
 

  )
}
